version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    tty: true
    restart: unless-stopped
    entrypoint: /bin/bash
    command: >
      -c "ollama serve & 
          sleep 5 && 
          ollama pull gemma3:4b && 
          ollama pull bge-m3 && 
          tail -f /dev/null"

volumes:
  qdrant_data:
  ollama_data:
